"""create GPUaaS core tables

Revision ID: 0fdbb1b3af61
Revises: 
Create Date: 2026-08-14 18:51:42.537144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fdbb1b3af61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_company_name'), 'customers', ['company_name'], unique=False)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    op.create_table('gpu_allocations',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('gpu_type', sa.String(length=50), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_allocations_customer_id'), 'gpu_allocations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_gpu_allocations_gpu_type'), 'gpu_allocations', ['gpu_type'], unique=False)
    op.create_index(op.f('ix_gpu_allocations_region'), 'gpu_allocations', ['region'], unique=False)
    op.create_table('gpu_jobs',
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('gpu_type', sa.String(length=50), nullable=False),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['gpu_allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gpu_jobs_allocation_id'), 'gpu_jobs', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_gpu_jobs_customer_id'), 'gpu_jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_gpu_jobs_external_id'), 'gpu_jobs', ['external_id'], unique=True)
    op.create_index(op.f('ix_gpu_jobs_status'), 'gpu_jobs', ['status'], unique=False)
    op.create_table('gpu_usage_events',
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('gpu_type', sa.String(length=50), nullable=False),
    sa.Column('gpu_hours', sa.Float(), nullable=False),
    sa.Column('utilization', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['gpu_allocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_gpu_usage_events_event_id')
    )
    op.create_index(op.f('ix_gpu_usage_events_allocation_id'), 'gpu_usage_events', ['allocation_id'], unique=False)
    op.create_index(op.f('ix_gpu_usage_events_customer_id'), 'gpu_usage_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_gpu_usage_events_event_id'), 'gpu_usage_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_gpu_usage_events_timestamp'), 'gpu_usage_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gpu_usage_events_timestamp'), table_name='gpu_usage_events')
    op.drop_index(op.f('ix_gpu_usage_events_event_id'), table_name='gpu_usage_events')
    op.drop_index(op.f('ix_gpu_usage_events_customer_id'), table_name='gpu_usage_events')
    op.drop_index(op.f('ix_gpu_usage_events_allocation_id'), table_name='gpu_usage_events')
    op.drop_table('gpu_usage_events')
    op.drop_index(op.f('ix_gpu_jobs_status'), table_name='gpu_jobs')
    op.drop_index(op.f('ix_gpu_jobs_external_id'), table_name='gpu_jobs')
    op.drop_index(op.f('ix_gpu_jobs_customer_id'), table_name='gpu_jobs')
    op.drop_index(op.f('ix_gpu_jobs_allocation_id'), table_name='gpu_jobs')
    op.drop_table('gpu_jobs')
    op.drop_index(op.f('ix_gpu_allocations_region'), table_name='gpu_allocations')
    op.drop_index(op.f('ix_gpu_allocations_gpu_type'), table_name='gpu_allocations')
    op.drop_index(op.f('ix_gpu_allocations_customer_id'), table_name='gpu_allocations')
    op.drop_table('gpu_allocations')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_name'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
