"""add xero invoice id

Revision ID: 184e24945722
Revises: 30cc9556dff0
Create Date: 2026-08-16 18:54:02.151540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184e24945722'
down_revision: Union[str, Sequence[str], None] = '30cc9556dff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('xero_invoice_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_invoices_xero_invoice_id'), 'invoices', ['xero_invoice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_xero_invoice_id'), table_name='invoices')
    op.drop_column('invoices', 'xero_invoice_id')
    # ### end Alembic commands ###
