"""add xero contact mapping

Revision ID: 30cc9556dff0
Revises: d31e4f7b783a
Create Date: 2026-08-16 03:02:21.421893

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30cc9556dff0"
down_revision: str | Sequence[str] | None = "d31e4f7b783a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "xero_connections", sa.Column("xero_contact_id", sa.String(length=100), nullable=True)
    )
    op.create_index(
        op.f("ix_xero_connections_xero_contact_id"),
        "xero_connections",
        ["xero_contact_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_xero_connections_xero_contact_id"), table_name="xero_connections")
    op.drop_column("xero_connections", "xero_contact_id")
    # ### end Alembic commands ###
