"""add gpuas outbox events

Revision ID: 63edb6577f88
Revises: 94a3f13e75f5
Create Date: 2026-08-15 06:26:20.069539

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "63edb6577f88"
down_revision: str | Sequence[str] | None = "94a3f13e75f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), server_default="pending", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_type"), "outbox_events", ["aggregate_type"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_available_at"), "outbox_events", ["available_at"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_event_type"), "outbox_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_status"), "outbox_events", ["status"], unique=False)
    op.drop_table("alembic_version_integration")
    op.drop_index(op.f("ix_integration_events_correlation_id"), table_name="integration_events")
    op.drop_index(op.f("ix_integration_events_event_id"), table_name="integration_events")
    op.drop_index(op.f("ix_integration_events_event_type"), table_name="integration_events")
    op.drop_index(
        op.f("ix_integration_events_event_type_occurred_at"), table_name="integration_events"
    )
    op.drop_index(op.f("ix_integration_events_occurred_at"), table_name="integration_events")
    op.drop_index(op.f("ix_integration_events_source"), table_name="integration_events")
    op.drop_index(op.f("ix_integration_events_status"), table_name="integration_events")
    op.drop_table("integration_events")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_events",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("source", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("source_event_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "occurred_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("correlation_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'received'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "retry_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("last_error", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("integration_events_pkey")),
        sa.UniqueConstraint(
            "event_id",
            name=op.f("integration_events_event_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "source",
            "source_event_id",
            name=op.f("uq_integration_events_source_event"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_integration_events_status"), "integration_events", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_integration_events_source"), "integration_events", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_integration_events_occurred_at"),
        "integration_events",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_events_event_type_occurred_at"),
        "integration_events",
        ["event_type", "occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_events_event_type"), "integration_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_integration_events_event_id"), "integration_events", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_integration_events_correlation_id"),
        "integration_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_table(
        "alembic_version_integration",
        sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_integration_pkc")),
    )
    op.drop_index(op.f("ix_outbox_events_status"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_event_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_available_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_type"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    # ### end Alembic commands ###
