"""add GPU capacity management

Revision ID: 94a3f13e75f5
Revises: 0fdbb1b3af61
Create Date: 2026-08-14 20:14:25.178205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94a3f13e75f5"
down_revision: str | Sequence[str] | None = "0fdbb1b3af61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gpu_capacity",
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("gpu_type", sa.String(length=50), nullable=False),
        sa.Column("total_gpus", sa.Integer(), nullable=False),
        sa.Column("allocated_gpus", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.String(length=50), server_default="active", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("region", "gpu_type", name="uq_gpu_capacity_region_gpu_type"),
    )
    op.create_index(op.f("ix_gpu_capacity_gpu_type"), "gpu_capacity", ["gpu_type"], unique=False)
    op.create_index(op.f("ix_gpu_capacity_region"), "gpu_capacity", ["region"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gpu_capacity_region"), table_name="gpu_capacity")
    op.drop_index(op.f("ix_gpu_capacity_gpu_type"), table_name="gpu_capacity")
    op.drop_table("gpu_capacity")
    # ### end Alembic commands ###
