"""add xero connections

Revision ID: d31e4f7b783a
Revises: cf97a8321be4
Create Date: 2026-08-16 02:56:29.966764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d31e4f7b783a"
down_revision: str | Sequence[str] | None = "cf97a8321be4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "xero_connections",
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=100), nullable=False),
        sa.Column("tenant_name", sa.String(length=255), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_xero_connections_customer_id"), "xero_connections", ["customer_id"], unique=True
    )
    op.create_index(
        op.f("ix_xero_connections_tenant_id"), "xero_connections", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_xero_connections_tenant_id"), table_name="xero_connections")
    op.drop_index(op.f("ix_xero_connections_customer_id"), table_name="xero_connections")
    op.drop_table("xero_connections")
    # ### end Alembic commands ###
